# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/my_gem/all/my_gem.rbi
#
# my_gem-0.1.0

module MyGem
end
class MyGem::Error < StandardError
end
